query myOrganizationList($listMembers: Boolean){
    myOrganizationList(listMembers: $listMembers){
        createdAt
        desc
        iName
        id
        images
        location
        name
        ownerId
        phone
        totalAmount
        type
        updatedAt
        users{
            email
            firstName
            id
            lastName
            organizations{
                createdAt
                desc
                iName
                id
                images
                location
                name
                ownerId
                phone
                totalAmount
                type
                updatedAt
                users{
                    email
                    firstName
                    id
                    lastName
                    status
                }
            }
            status
        }
    }
}